
package View;

import Dao.AgendaDAO;
import Dao.ClienteDAO;
import Dao.DiscoDAO;
import Dao.PagamentoDAO;
import Dao.SalaDAO;
import Entity.Agenda;
import Entity.Cliente;
import Entity.Disco;
import Entity.Gravacao;
import Entity.Historico;
import Entity.Pagamento;
import Entity.Sala;
import Exception.HorarioOcupadoException;
import java.sql.Date;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Exception.ValorSuperiorException;


/**
 *
 * @author Tay
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {    
        initComponents();
        
        Cliente c = null;
         mostrarTelaClientes();
         mostrarTelaHorariosSala();
         atualizaHorariosMarcados();
         atualizaTabelaDiscos();
         atualizaPagamentos();
         lblValorHora.setText(" 25 R$.");
         
          tpAbas.getDisabledIconAt(3);
    } 
   SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
   SimpleDateFormat sdf2 = new SimpleDateFormat("HH:mm");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpAbas = new javax.swing.JTabbedPane();
        jPanelMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHorariosMain = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbSalaMain = new javax.swing.JComboBox();
        txtBuscarMain = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanelCliente = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarCliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblResidencial = new javax.swing.JLabel();
        btnExcluirCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        btnHistoricoCliente = new javax.swing.JButton();
        btnVerDadosCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstClientes = new javax.swing.JList();
        btnCadastrarCliente = new javax.swing.JButton();
        btnMarcarHorario = new javax.swing.JButton();
        jPanelAgendamento = new javax.swing.JPanel();
        cbClientes = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cbSala = new javax.swing.JComboBox();
        lblAgendado = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        txtHorarioInicial = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        txtHorarioTermino = new javax.swing.JFormattedTextField();
        btnAgendar = new javax.swing.JButton();
        btnDesmarcar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstHorariosCliente = new javax.swing.JList();
        jLabel21 = new javax.swing.JLabel();
        AlterarHorario = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblValorHora = new javax.swing.JLabel();
        jPanelGravacoes = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHorariosMarcados = new javax.swing.JTable();
        txtBuscarGravacoes = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstClientesCadastrarDiscos = new javax.swing.JList();
        jPanel15 = new javax.swing.JPanel();
        btnCadastrarDisco = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        lblClienteTelaG = new javax.swing.JLabel();
        lblmensagemGravaçao = new javax.swing.JLabel();
        btnVerHorarios = new javax.swing.JButton();
        jPanelDistribuicao = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        txtBuscarDiscos = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblDiscos = new javax.swing.JTable();
        btnAlterarDisco = new javax.swing.JButton();
        btnVerDisco = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jSpinnerCópiasDisco = new javax.swing.JSpinner();
        jLabel47 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtValorCópia = new javax.swing.JTextField();
        btnProduzirCopias = new javax.swing.JButton();
        jPanelFinanceiro = new javax.swing.JPanel();
        txtBuscarPagamento = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblHorariosFinanceiro = new javax.swing.JTable();
        btnPago = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnPagoParcialmente = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        txtPagoParcialmente = new javax.swing.JTextField();
        lblMensagemF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpAbas.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaption), javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption, 2)));
        tpAbas.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tpAbas.setAlignmentX(2.5F);
        tpAbas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblHorariosMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Sala", "Data", "Horário Inicio", "Horário Termino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHorariosMain);

        jLabel1.setText("Proximos Horários:");

        jLabel12.setText("Filtrar Exibição:");

        jLabel13.setText("Sala:");

        jLabel14.setText("Nome:");

        cbSalaMain.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        cbSalaMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSalaMainActionPerformed(evt);
            }
        });
        cbSalaMain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbSalaMainKeyReleased(evt);
            }
        });

        txtBuscarMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarMainActionPerformed(evt);
            }
        });

        btnOK.setText("Ok");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logotipo estudio 3.png"))); // NOI18N

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(cbSalaMain, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnOK)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(41, 349, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(12, 12, 12)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtBuscarMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cbSalaMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel17))
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        tpAbas.addTab("Main", jPanelMain);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Buscar:");

        txtBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarClienteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Dados Cliente:");

        jLabel4.setText("Nome:");

        jLabel5.setText("CPF:");

        jLabel8.setText("Tel Residencial:");

        jLabel9.setText("Tel Celular:");

        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        btnAlterarCliente.setText("Alterar");
        btnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClienteActionPerformed(evt);
            }
        });

        jLabel28.setText("Agendamentos Anteriores:");

        btnHistoricoCliente.setText("Histórico");
        btnHistoricoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoClienteActionPerformed(evt);
            }
        });

        btnVerDadosCliente.setText("Ver Dados Completos");
        btnVerDadosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDadosClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnVerDadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnAlterarCliente)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnExcluirCliente))
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnHistoricoCliente)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirCliente)
                    .addComponent(btnAlterarCliente))
                .addGap(18, 18, 18)
                .addComponent(btnVerDadosCliente)
                .addGap(54, 54, 54)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(btnHistoricoCliente)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        lstClientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstClientesValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstClientes);

        btnCadastrarCliente.setBackground(new java.awt.Color(241, 228, 252));
        btnCadastrarCliente.setText("Cadastrar Novo Cliente");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        btnMarcarHorario.setBackground(new java.awt.Color(233, 222, 244));
        btnMarcarHorario.setText("Marcar Horário");
        btnMarcarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarHorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrarCliente)
                            .addComponent(btnMarcarHorario))
                        .addGap(64, 64, 64))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteLayout.createSequentialGroup()
                                .addGap(0, 17, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnMarcarHorario)
                        .addGap(26, 26, 26)
                        .addComponent(btnCadastrarCliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpAbas.addTab("  Cliente  ", jPanelCliente);

        cbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClientesActionPerformed(evt);
            }
        });

        jLabel15.setText("Cliente:");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setText("Sala:");

        cbSala.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        cbSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSalaActionPerformed(evt);
            }
        });

        lblAgendado.setForeground(new java.awt.Color(95, 53, 95));
        lblAgendado.setText("                            ");

        jLabel18.setText("Data:");

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        jLabel19.setText("Horário:");

        try {
            txtHorarioInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel20.setText("á");

        try {
            txtHorarioTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnAgendar.setText("Agendar");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });

        btnDesmarcar.setText("Desmarcar");
        btnDesmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesmarcarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cbSala, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addComponent(lblAgendado))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHorarioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txtHorarioTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnAgendar)
                .addGap(18, 18, 18)
                .addComponent(btnDesmarcar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAgendado)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtHorarioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtHorarioTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgendar)
                    .addComponent(btnDesmarcar))
                .addGap(33, 33, 33))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane4.setViewportView(lstHorariosCliente);

        jLabel21.setText("Horários");

        AlterarHorario.setText("Alterar");
        AlterarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarHorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(AlterarHorario)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AlterarHorario)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(216, 214, 220));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel22.setText("Valor Total:");

        jLabel23.setText("-");

        jLabel26.setText("Valor Hora:");

        lblValorHora.setText("-");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(lblValorHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelAgendamentoLayout = new javax.swing.GroupLayout(jPanelAgendamento);
        jPanelAgendamento.setLayout(jPanelAgendamentoLayout);
        jPanelAgendamentoLayout.setHorizontalGroup(
            jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanelAgendamentoLayout.setVerticalGroup(
            jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );

        tpAbas.addTab("Agendamento", jPanelAgendamento);

        jLabel30.setText("Buscar Clientes:");

        tblHorariosMarcados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Horário", "Dia", "Custo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblHorariosMarcados);

        txtBuscarGravacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarGravacoesActionPerformed(evt);
            }
        });
        txtBuscarGravacoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarGravacoesKeyReleased(evt);
            }
        });

        lstClientesCadastrarDiscos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstClientesCadastrarDiscosKeyReleased(evt);
            }
        });
        lstClientesCadastrarDiscos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstClientesCadastrarDiscosValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(lstClientesCadastrarDiscos);

        jPanel15.setBackground(new java.awt.Color(216, 214, 220));
        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCadastrarDisco.setText("Cadastrar Disco");
        btnCadastrarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarDiscoActionPerformed(evt);
            }
        });

        jLabel43.setText("Cliente:");

        lblClienteTelaG.setText("-");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClienteTelaG, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(btnCadastrarDisco)
                .addGap(53, 53, 53))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarDisco)
                    .addComponent(jLabel43)
                    .addComponent(lblClienteTelaG))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnVerHorarios.setText("Ver");
        btnVerHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHorariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGravacoesLayout = new javax.swing.GroupLayout(jPanelGravacoes);
        jPanelGravacoes.setLayout(jPanelGravacoesLayout);
        jPanelGravacoesLayout.setHorizontalGroup(
            jPanelGravacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGravacoesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelGravacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelGravacoesLayout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblmensagemGravaçao, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBuscarGravacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelGravacoesLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(btnVerHorarios))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanelGravacoesLayout.setVerticalGroup(
            jPanelGravacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGravacoesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelGravacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(lblmensagemGravaçao, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarGravacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanelGravacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelGravacoesLayout.createSequentialGroup()
                        .addComponent(btnVerHorarios)
                        .addGap(185, 185, 185))
                    .addGroup(jPanelGravacoesLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        tpAbas.addTab("Gravações", jPanelGravacoes);

        jLabel45.setText("Buscar Disco:");

        txtBuscarDiscos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarDiscosActionPerformed(evt);
            }
        });
        txtBuscarDiscos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarDiscosKeyReleased(evt);
            }
        });

        tblDiscos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome Disco", "Cliente", "Cópias Vendidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblDiscos);

        btnAlterarDisco.setText("Alterar");
        btnAlterarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarDiscoActionPerformed(evt);
            }
        });

        btnVerDisco.setText("Ver");
        btnVerDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDiscoActionPerformed(evt);
            }
        });

        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel46.setText("Numero de Cópias:");

        jLabel47.setText("Valor Total:");

        lblValorTotal.setText("-");

        jLabel49.setText("Valor por Cópia:");

        btnProduzirCopias.setText("Produzir Cópias");
        btnProduzirCopias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduzirCopiasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerCópiasDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorCópia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addGap(18, 18, 18)
                        .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProduzirCopias))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jSpinnerCópiasDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(lblValorTotal))
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(txtValorCópia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnProduzirCopias)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDistribuicaoLayout = new javax.swing.GroupLayout(jPanelDistribuicao);
        jPanelDistribuicao.setLayout(jPanelDistribuicaoLayout);
        jPanelDistribuicaoLayout.setHorizontalGroup(
            jPanelDistribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuicaoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelDistribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscarDiscos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDistribuicaoLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDistribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerDisco)
                            .addComponent(btnAlterarDisco))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanelDistribuicaoLayout.setVerticalGroup(
            jPanelDistribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuicaoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarDiscos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanelDistribuicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDistribuicaoLayout.createSequentialGroup()
                        .addComponent(btnVerDisco)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarDisco))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        tpAbas.addTab("Distribuição", jPanelDistribuicao);

        txtBuscarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPagamentoActionPerformed(evt);
            }
        });
        txtBuscarPagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarPagamentoKeyReleased(evt);
            }
        });

        jLabel41.setText("Buscar por Cliente:");

        tblHorariosFinanceiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Cliente", "Descrição", "Custo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblHorariosFinanceiro);

        btnPago.setText("Pago");
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPagoParcialmente.setText("Pago Parcialmente");
        btnPagoParcialmente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoParcialmenteActionPerformed(evt);
            }
        });

        jLabel42.setText("Valor:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPagoParcialmente)
                    .addComponent(txtPagoParcialmente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtPagoParcialmente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnPagoParcialmente)
                .addContainerGap())
        );

        lblMensagemF.setText("-");

        javax.swing.GroupLayout jPanelFinanceiroLayout = new javax.swing.GroupLayout(jPanelFinanceiro);
        jPanelFinanceiro.setLayout(jPanelFinanceiroLayout);
        jPanelFinanceiroLayout.setHorizontalGroup(
            jPanelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinanceiroLayout.createSequentialGroup()
                .addGroup(jPanelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelFinanceiroLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBuscarPagamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                            .addComponent(lblMensagemF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFinanceiroLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanelFinanceiroLayout.setVerticalGroup(
            jPanelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinanceiroLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel41)
                .addGap(11, 11, 11)
                .addComponent(txtBuscarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMensagemF)
                .addGap(29, 29, 29))
        );

        tpAbas.addTab("Financeiro", jPanelFinanceiro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpAbas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpAbas.getAccessibleContext().setAccessibleName("Tab1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagoParcialmenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoParcialmenteActionPerformed
        Pagamento p = new Pagamento();
        int linha = tblHorariosFinanceiro.getSelectedRow();
        int id = Integer.parseInt(tblHorariosFinanceiro.getValueAt(linha, 0).toString());

        PagamentoDAO dao = new PagamentoDAO();
        p = dao.getPagamentoById(id);

        double valor = p.getValor();
        double v2 = Double.parseDouble(txtPagoParcialmente.getText());

        try {
            double d = p.PagarParcialmente(valor, v2);
            p.setDescricao(p.getDescricao());       
            p.setValor(d);
            p.setIdCliente(p.getIdCliente());
            p.setCustoPorHora(p.getCustoPorHora());
            
            dao.update(p);
            atualizaPagamentos();

        } catch (ValorSuperiorException ex) {
            JOptionPane.showMessageDialog(this, "Valor Superior ao Custo Total!");
        }
      
        atualizaPagamentos();
        lblMensagemF.setText("Pago Parcialmente.");
    }//GEN-LAST:event_btnPagoParcialmenteActionPerformed

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
        Pagamento p = new Pagamento();
        int linha = tblHorariosFinanceiro.getSelectedRow();
        int id = Integer.parseInt(tblHorariosFinanceiro.getValueAt(linha, 0).toString());
        
        PagamentoDAO dao = new PagamentoDAO();
        
        dao.delete(id);

         atualizaPagamentos();
         
         lblMensagemF.setText("Valor Total Pago!");
    }//GEN-LAST:event_btnPagoActionPerformed

    private void txtBuscarPagamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPagamentoKeyReleased
        ClienteDAO dao = new ClienteDAO();
        List<Cliente> encontrados = dao.listarClientes(txtBuscarPagamento.getText());
        mostrarTelaClientes(encontrados);
    }//GEN-LAST:event_txtBuscarPagamentoKeyReleased

    private void txtBuscarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPagamentoActionPerformed

    private void btnProduzirCopiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduzirCopiasActionPerformed
        DiscoDAO dao = new DiscoDAO();
        Disco objDisco = new Disco();
        
        int linha = tblDiscos.getSelectedRow();
        int id = Integer.parseInt(tblDiscos.getValueAt(linha, 0).toString());
        objDisco = dao.getDiscosById(id);
        
        int numero = (int) jSpinnerCópiasDisco.getValue();
         objDisco.incluirCopias(numero);
         
        dao.update(objDisco);      
        atualizaTabelaDiscos();
    }//GEN-LAST:event_btnProduzirCopiasActionPerformed

    private void btnVerDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDiscoActionPerformed
        int linha = tblDiscos.getSelectedRow();
        int id = Integer.parseInt(tblDiscos.getValueAt(linha, 0).toString());

        DiscoDAO dao = new DiscoDAO();
        Disco disco = dao.getDiscosById(id);

        TelaVerDisco objTelaVerDisco = new TelaVerDisco(this, true, disco);

        objTelaVerDisco.setVisible(true);

    }//GEN-LAST:event_btnVerDiscoActionPerformed

    private void btnAlterarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarDiscoActionPerformed
        alterar = true;
        int linha = tblDiscos.getSelectedRow();
        id = Integer.parseInt(tblDiscos.getValueAt(linha, 0).toString());
        DiscoDAO dao = new DiscoDAO();
        Disco disco = dao.getDiscosById(id);

        System.out.print(linha);

        Cliente cliente = null;

        TelaCadastroDisco objTelaCadastroDisco = new TelaCadastroDisco(this, true, disco, id, objGravacao,
            alterar, cliente);

        objTelaCadastroDisco.setVisible(true);

        atualizaTabelaDiscos();
    }//GEN-LAST:event_btnAlterarDiscoActionPerformed

    private void txtBuscarDiscosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarDiscosKeyReleased
        DiscoDAO dao = new DiscoDAO();
        List<Disco> encontrados = dao.listarDiscos(txtBuscarDiscos.getText());
        mostrarDiscos(encontrados);
    }//GEN-LAST:event_txtBuscarDiscosKeyReleased

    private void txtBuscarDiscosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarDiscosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarDiscosActionPerformed

    private void btnVerHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHorariosActionPerformed
       
        
    }//GEN-LAST:event_btnVerHorariosActionPerformed

    private void btnCadastrarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarDiscoActionPerformed
        alterar = false;
        //Disco disco = (Disco) lstClientesCadastarDisco.getSelectedValue();
        Disco disco = null;
        Cliente cliente = (Cliente) lstClientesCadastrarDiscos.getSelectedValue();

        TelaCadastroDisco objTelaCadastroDisco = new TelaCadastroDisco(this, true, disco, id, objGravacao,
            alterar, cliente);

        objTelaCadastroDisco.setVisible(true);

        atualizaTabelaDiscos();
    }//GEN-LAST:event_btnCadastrarDiscoActionPerformed

    private void lstClientesCadastrarDiscosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstClientesCadastrarDiscosValueChanged
        Cliente c = (Cliente) lstClientesCadastrarDiscos.getSelectedValue();
        lblClienteTelaG.setText(c.getNome());
    }//GEN-LAST:event_lstClientesCadastrarDiscosValueChanged

    private void lstClientesCadastrarDiscosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstClientesCadastrarDiscosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lstClientesCadastrarDiscosKeyReleased

    private void txtBuscarGravacoesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarGravacoesKeyReleased
        ClienteDAO dao = new ClienteDAO();
        List<Cliente> encontrados = dao.listarClientes(txtBuscarGravacoes.getText());
        mostrarTelaClientes(encontrados);
    }//GEN-LAST:event_txtBuscarGravacoesKeyReleased

    private void txtBuscarGravacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarGravacoesActionPerformed

    }//GEN-LAST:event_txtBuscarGravacoesActionPerformed

    private void AlterarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarHorarioActionPerformed
        hSel = (Sala) lstHorariosCliente.getSelectedValue();
        alterarA = true;
        //txtData.setText(hSel.getData()+"");
        sdf.format(hSel.getData());                             //Arrumar data
        txtData.setText(sdf.format(hSel.getData()));
        txtHorarioInicial.setText(hSel.getHorarioInicio()+"");
        txtHorarioTermino.setText(hSel.getHorarioTermino()+"");
        cbSala.setSelectedItem(hSel.getNumero());

        btnAgendar.setText("Alterar");

    }//GEN-LAST:event_AlterarHorarioActionPerformed

    private void btnDesmarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesmarcarActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja mesmo desmarcar?", "Exclusão", 0);
        if (resposta == 0) {

            SalaDAO dao = new SalaDAO();
            Sala s = (Sala) lstHorariosCliente.getSelectedValue();
            int id = s.getId();


            dao.delete(id);
        }
        Cliente c = null; //
        mostrarTelaHorariosSala();
        atualizaHorariosMarcados();
    }//GEN-LAST:event_btnDesmarcarActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        //Agenda
        Agenda a = new Agenda() {};
        int i = Integer.parseInt((String) cbSala.getSelectedItem());

        a.setSala(i);
        AgendaDAO daoA = new AgendaDAO();
        daoA.insert(a);

        //Sala
        Cliente c = (Cliente) lstClientes.getSelectedValue();

        if(alterarA == false){

            Sala objSala = new Sala();

            objSala.setIdCliente(c.getId());
            objSala.setNumero(cbSala.getSelectedIndex()+1);

            //data
            try {
                objSala.setData(sdf.parse(txtData.getText()));
            } catch(ParseException e ) {
                e.printStackTrace();
            }
            //horario
            try {
                objSala.setHorarioInicio(sdf2.parse(txtHorarioInicial.getText()));
                objSala.setHorarioTermino(sdf2.parse(txtHorarioTermino.getText()));
            } catch(ParseException e ) {
                e.printStackTrace();
            }

            a.adicionarSala(objSala);

            //Cliente c = (Cliente) cbClientes.getSelectedItem();
            c = (Cliente) cSel;

            try {
                adicionarHorario(objSala);

            } catch (HorarioOcupadoException ex) {
                JOptionPane.showMessageDialog(this, "Horario já Ocupado!");
            }

            //banco de dados Sala
            SalaDAO dao = new SalaDAO();
            dao.insert(objSala);

            lblAgendado.setText("Horario Agendado");

            //Calcular horas/ Pagamento
            PagamentoDAO daoP = new PagamentoDAO();
            Pagamento p = new Pagamento();

            int d = diffHoras(objSala.getHorarioInicio(), objSala.getHorarioTermino());
            double valor = p.CalcularCustoAgendamento(d);

            p.setValor(valor);
            p.setDescricao("Agendamento de Sala");
            p.setIdCliente(c.getId());
            p.setCustoPorHora(p.getCustoPorHora());

            daoP.insert(p);

            atualizaPagamentos();
            //
        }
        else{

            hSel.setNumero(cbSala.getSelectedIndex()+1);
            //data
            try {
                hSel.setData(sdf.parse(txtData.getText()));
            } catch(ParseException e ) {
                e.printStackTrace();
            }
            //horario
            try {
                hSel.setHorarioInicio(sdf2.parse(txtHorarioInicial.getText()));
                hSel.setHorarioTermino(sdf2.parse(txtHorarioTermino.getText()));
            } catch(ParseException e ) {
                e.printStackTrace();
            }
            //hSel.setHorarioInicio(null);

            SalaDAO dao = new SalaDAO();
            dao.update(hSel);

            lblAgendado.setText("Horário Alterado.");

            //Calcular horas/ Pagamento
            diffHoras(hSel.getHorarioInicio(), hSel.getHorarioTermino());

        }

        mostrarTelaHorariosSala();

        // calcularValorTotal(agenda);
        calcularValorTotal();

        limparCampos();
        atualizaHorariosMarcados();
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void cbSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSalaActionPerformed

    private void cbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClientesActionPerformed

        //cbClientes.addItem(EnumClientes.objCliente);

    }//GEN-LAST:event_cbClientesActionPerformed

    private void btnMarcarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarHorarioActionPerformed
        cSel = (Cliente) lstClientes.getSelectedValue();
        String nome = cSel.getNome();
        //cbClientes.setModel((ComboBoxModel) nome);
        cbClientes.addItem(nome);
        cbClientes.setSelectedItem(nome);
        //jPanelAgendamento.setVisible(rootPaneCheckingEnabled);
        tpAbas.setSelectedIndex(2);
    }//GEN-LAST:event_btnMarcarHorarioActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        alterar = false;
        //Cliente cliente = (Cliente) lstClientes.getSelectedValue();
        //Cliente cliente = new Cliente();
        Cliente cliente = null;
        TelaCadastroCliente objTelaCadastroCliente = new TelaCadastroCliente(this, true, cliente,
            alterar);

        objTelaCadastroCliente.setVisible(true);

        mostrarTelaClientes();

        cbClientes.addItem(cliente);
        //EnumClientes.(cliente);
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void lstClientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstClientesValueChanged
        preencherDados();
    }//GEN-LAST:event_lstClientesValueChanged

    private void btnVerDadosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDadosClienteActionPerformed
        Cliente cliente = (Cliente) lstClientes.getSelectedValue();

        TelaVerCliente objTelaVerCliente = new TelaVerCliente(this, true, cliente);

        objTelaVerCliente.setVisible(true);
    }//GEN-LAST:event_btnVerDadosClienteActionPerformed

    private void btnHistoricoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoClienteActionPerformed
        SalaDAO dao = new SalaDAO();

        Cliente cliente = (Cliente) lstClientes.getSelectedValue();

        Sala sala = dao.getSalaByIdCliente(cliente.getId());

        TelaHistorico tela = new TelaHistorico(this, true, cliente, sala, gravado);

        tela.setVisible(true);
    }//GEN-LAST:event_btnHistoricoClienteActionPerformed

    private void btnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClienteActionPerformed
        alterar = true;

        Cliente cliente = (Cliente) lstClientes.getSelectedValue();

        TelaCadastroCliente objTelaCadastroCliente = new TelaCadastroCliente(this, true, cliente,
            alterar);

        objTelaCadastroCliente.setVisible(true);

        mostrarTelaClientes();

    }//GEN-LAST:event_btnAlterarClienteActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir?", "Exclusão", 0);
        if (resposta == 0) {

            ClienteDAO dao = new ClienteDAO();
            Cliente c = (Cliente) lstClientes.getSelectedValue();
            int id = c.getId();
            // int c = lstClientes.getSelectedIndex();

            dao.delete(id);

        }
        mostrarTelaClientes();

    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void txtBuscarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClienteKeyReleased
        ClienteDAO dao = new ClienteDAO();
        List<Cliente> encontrados = dao.listarClientes(txtBuscarCliente.getText());
        mostrarTelaClientes(encontrados);
    }//GEN-LAST:event_txtBuscarClienteKeyReleased

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        SalaDAO dao = new SalaDAO();
        List<Sala> encontrados = dao.listarSalas(txtBuscarMain.getText(), (int)cbSalaMain.getSelectedIndex()+1);
        mostrarSala(encontrados);
    }//GEN-LAST:event_btnOKActionPerformed

    private void txtBuscarMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarMainActionPerformed

    private void cbSalaMainKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbSalaMainKeyReleased

    }//GEN-LAST:event_cbSalaMainKeyReleased

    private void cbSalaMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSalaMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSalaMainActionPerformed

    boolean alterar= false;
    
    boolean alterarA = false;
    
       public int diffHoras(java.util.Date dataInicio, java.util.Date dataFim) {
        GregorianCalendar calInicio = new GregorianCalendar();
        GregorianCalendar calFim = new GregorianCalendar();

        calInicio.setTime(dataInicio);
        calFim.setTime(dataFim);

        // Calcula a diferença entre hora fim e a hora inicio
        long diff = calFim.getTimeInMillis() - calInicio.getTimeInMillis();

        // Quantidade de milissegundos em uma hora
        long tempoHora = 1000 * 60 * 60;

        return (int) (diff / tempoHora);
    }
    
    boolean e;
    
    public void adicionarHorario(Sala objSala) throws HorarioOcupadoException{
         SalaDAO dao = new SalaDAO();
         List<Sala> listarSala = dao.listarSala();
        
        //pega o modelo da Tabela e coloca na variavel "model"
         DefaultTableModel model = 
                (DefaultTableModel) this.tblHorariosMain.getModel();
        //insere na tabela o número de linhas que a lista tem
        model.setRowCount(listarSala.size());
        
        //laço para inserir os dados dos objetos na Tabela
        for (int i = 0; i < listarSala.size(); i++) {
            
            model.setValueAt(listarSala.get(i).getClass().getName(), i, 0);
            model.setValueAt(listarSala.get(i).getNumero(), i, 1);
            model.setValueAt(listarSala.get(i).getData(), i, 2);
            model.setValueAt(listarSala.get(i).getHorarioInicio(), i, 3);
            model.setValueAt(listarSala.get(i).getHorarioTermino(), i, 4);     
           
            int n = listarSala.get(i).getNumero();
            Date d = (Date) listarSala.get(i).getData();
            Time t1 = (Time) listarSala.get(i).getHorarioInicio();
            Time t2 = (Time) listarSala.get(i).getHorarioTermino();
            
         if(n == objSala.getNumero() && d == objSala.getData() && 
                 (t1== objSala.getHorarioInicio() || t2== objSala.getHorarioTermino())){
               throw new HorarioOcupadoException();
        }
         else{
             e = false;
         }
        }
       
    }
    
    Gravacao objGravacao = new Gravacao() {};
    boolean gravado = false;
    
    int id;

    
    Cliente cSel;
    Sala hSel;
            
    
    //txtBuscarCliente Key e txtBuscarGravacoes Key
     private void mostrarTelaClientes(List<Cliente> contatosQueQueroMostrar) {
        DefaultListModel modelo = new DefaultListModel();
        for (Cliente cliente : contatosQueQueroMostrar) {
            modelo.addElement(cliente);
        }
        lstClientes.setModel(modelo);
        lstClientesCadastrarDiscos.setModel(modelo);
    }
     
    
    //txtBuscarDiscos Key
     private void mostrarDiscos(List<Disco> discoMostrar) {    
         DiscoDAO dao = new DiscoDAO();
         List<Disco> listarDiscos = dao.listarDiscos();
         
        //pega o modelo da Tabela e coloca na variavel "model"
         DefaultTableModel model = 
                (DefaultTableModel) this.tblDiscos.getModel();
        //insere na tabela o número de linhas que a lista tem
        model.setRowCount(listarDiscos.size());
        
        for (Disco d : discoMostrar) {
            
          //   model.addColumn(d);
        //}
        
        //laço para inserir os dados dos objetos na Tabela
        for (int i = 0; i < listarDiscos.size(); i++) {
            
            model.setValueAt(listarDiscos.get(i).getId(), i, 0);
            model.setValueAt(listarDiscos.get(i).getNome(), i, 1);
           model.setValueAt(listarDiscos.get(i).getArtista(), i, 2);
           model.setValueAt(listarDiscos.get(i).getCopiasProduzidas(), i, 3);
           
        }
        }
    }
    
    //
     private void mostrarSala(List<Sala> salaMostrar) {    
         SalaDAO dao = new SalaDAO();
         List<Sala> listarSalas = dao.listarSala();
         
        //pega o modelo da Tabela e coloca na variavel "model"
         DefaultTableModel model = 
                (DefaultTableModel) this.tblHorariosMain.getModel();
        //insere na tabela o número de linhas que a lista tem
        model.setRowCount(listarSalas.size());
        
        for (Sala s : salaMostrar) {
            
          //   model.addColumn(d);
        //}
        
        //laço para inserir os dados dos objetos na Tabela
        for (int i = 0; i < listarSalas.size(); i++) {
            
            model.setValueAt(listarSalas.get(i).getClass().getName(), i, 0);
            model.setValueAt(listarSalas.get(i).getNumero(), i, 1);
            model.setValueAt(listarSalas.get(i).getData(), i, 2);
            model.setValueAt(listarSalas.get(i).getHorarioInicio(), i, 3);
            model.setValueAt(listarSalas.get(i).getHorarioTermino(), i, 4);    
           
        }
        }
    }
     
     
    //List
     private void mostrarTelaClientes() {
        ClienteDAO daoC = new ClienteDAO();
        List<Cliente> listarCliente = daoC.listarClientes();
        
        DefaultListModel modelo = new DefaultListModel();
        //modelo.setRowCount(listarCliente.size());
        for (Cliente cliente : listarCliente) {
            modelo.addElement(cliente);
        }
        lstClientes.setModel(modelo);
    }
      
     private void mostrarTelaHorariosSala() {
        SalaDAO daoS = new SalaDAO();
        List<Sala> listarDisco = daoS.listarSala();
           
        DefaultListModel modelo = new DefaultListModel();     
        for (Sala hSala : listarDisco) {
           // for (Agenda a: pegarSala) {
            //     modelo.addElement(a);
                 
           // }
             modelo.addElement(hSala);
        }
        lstHorariosCliente.setModel(modelo);
    }
     
     
    //Tables
     private void atualizaTabelaDiscos() {    
         DiscoDAO dao = new DiscoDAO();
         List<Disco> listarDiscos = dao.listarDiscos();
         
        ClienteDAO daoC = new ClienteDAO();
        List<Cliente> listarCliente = daoC.listarClientes();  //mostrar cliente
         
        //pega o modelo da Tabela e coloca na variavel "model"
         DefaultTableModel model = 
                (DefaultTableModel) this.tblDiscos.getModel();
        //insere na tabela o número de linhas que a lista tem
        model.setRowCount(listarDiscos.size());
       // model.setRowCount(listarCliente.size()); //Cliente
        
        //laço para inserir os dados dos objetos na Tabela
       for (int i = 0; i < listarDiscos.size(); i++) {
            
           model.setValueAt(listarDiscos.get(i).getId(), i, 0);
           model.setValueAt(listarDiscos.get(i).getNome(), i, 1);
           model.setValueAt(listarDiscos.get(i).getArtista(), i, 2);
           model.setValueAt(listarDiscos.get(i).getCopiasProduzidas(), i, 3);
           
        }
        
        //for (int i = 0; i < listarCliente.size(); i++) {           
         //  model.setValueAt(listarCliente.get(i).getId(), i, 1); //cliente
        //}
          
    }
     
     private void atualizaHorariosMarcados() {    
         SalaDAO dao = new SalaDAO();
         List<Sala> listarSala = dao.listarSala();
         
         //ClienteDAO daoC = new ClienteDAO();
         
        //pega o modelo da Tabela e coloca na variavel "model"
         DefaultTableModel model = 
                (DefaultTableModel) this.tblHorariosMain.getModel();
        //insere na tabela o número de linhas que a lista tem
        model.setRowCount(listarSala.size());
            
        
        //laço para inserir os dados dos objetos na Tabela
        for (int i = 0; i < listarSala.size(); i++) {
            
            model.setValueAt(listarSala.get(i).getIdCliente(), i, 0);
            model.setValueAt(listarSala.get(i).getNumero(), i, 1);
            model.setValueAt(listarSala.get(i).getData(), i, 2);
            model.setValueAt(listarSala.get(i).getHorarioInicio(), i, 3);
            model.setValueAt(listarSala.get(i).getHorarioTermino(), i, 4);     
            //model.setValueAt(listarSala.get(i).getCustoPorHora(), i, 4); //tenho q pegar custo total
        }
       
    }
     
      private void atualizaPagamentos() {    
         PagamentoDAO dao = new PagamentoDAO();
         List<Pagamento> listarP = dao.listarPagamento();
         
         //ClienteDAO daoC = new ClienteDAO();
         
        //pega o modelo da Tabela e coloca na variavel "model"
         DefaultTableModel model = 
                (DefaultTableModel) this.tblHorariosFinanceiro.getModel();
        //insere na tabela o número de linhas que a lista tem
        model.setRowCount(listarP.size());
            
        
        //laço para inserir os dados dos objetos na Tabela
        for (int i = 0; i < listarP.size(); i++) {
            
            model.setValueAt(listarP.get(i).getIdPagamento(), i, 0);
            model.setValueAt(listarP.get(i).getIdCliente(), i, 1);
            model.setValueAt(listarP.get(i).getDescricao(), i, 2);
            model.setValueAt(listarP.get(i).getValor(), i, 3);
            
        }
       
    }
     
     
     private void calcularValorTotal(){
         
         //agenda.getListaSala().get(id);
           
     }
     
     private void preencherDados() {
        Cliente c = (Cliente) lstClientes.getSelectedValue();
        
        lblNome.setText(c.getNome());
        lblCPF.setText(c.getCPF());
        lblCelular.setText(c.getTelCelular());
        lblResidencial.setText(c.getTelResidencial());
        
     } 
     
     private void limparCampos() {
        txtData.setText("");
        txtHorarioInicial.setText("");
        txtHorarioTermino.setText("");
        cbSala.setSelectedIndex(0);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarHorario;
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnAlterarDisco;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarDisco;
    private javax.swing.JButton btnDesmarcar;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnHistoricoCliente;
    private javax.swing.JButton btnMarcarHorario;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPago;
    private javax.swing.JButton btnPagoParcialmente;
    private javax.swing.JButton btnProduzirCopias;
    private javax.swing.JButton btnVerDadosCliente;
    private javax.swing.JButton btnVerDisco;
    private javax.swing.JButton btnVerHorarios;
    private javax.swing.JComboBox cbClientes;
    private javax.swing.JComboBox cbSala;
    private javax.swing.JComboBox cbSalaMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelAgendamento;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelDistribuicao;
    private javax.swing.JPanel jPanelFinanceiro;
    private javax.swing.JPanel jPanelGravacoes;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner jSpinnerCópiasDisco;
    private javax.swing.JLabel lblAgendado;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblClienteTelaG;
    private javax.swing.JLabel lblMensagemF;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblResidencial;
    private javax.swing.JLabel lblValorHora;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblmensagemGravaçao;
    private javax.swing.JList lstClientes;
    private javax.swing.JList lstClientesCadastrarDiscos;
    private javax.swing.JList lstHorariosCliente;
    private javax.swing.JTable tblDiscos;
    private javax.swing.JTable tblHorariosFinanceiro;
    private javax.swing.JTable tblHorariosMain;
    private javax.swing.JTable tblHorariosMarcados;
    private javax.swing.JTabbedPane tpAbas;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtBuscarDiscos;
    private javax.swing.JTextField txtBuscarGravacoes;
    private javax.swing.JTextField txtBuscarMain;
    private javax.swing.JTextField txtBuscarPagamento;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtHorarioInicial;
    private javax.swing.JFormattedTextField txtHorarioTermino;
    private javax.swing.JTextField txtPagoParcialmente;
    private javax.swing.JTextField txtValorCópia;
    // End of variables declaration//GEN-END:variables
}
